calebporzio/sushi

src/Sushi.php

When running `phpunit` on PHP 7.4.2 homebrew OSX I got the error:
> 1) Tests\SushiTest::not_adding_rows_property_throws_an_error
Failed asserting that exception message 'Trying to access array offset on value of type null' contains 'Sushi: $rows property not found on model: Tests\Bar'.
This comes from referencing an array that doesn't exist (and grabbing its first value) here:
https://github.com/calebporzio/sushi/blob/c42bd67209029e2eaf6f0950cddf696d352b476e/src/Sushi.php#L70-L71
before checking if it's empty here:
https://github.com/calebporzio/sushi/blob/c42bd67209029e2eaf6f0950cddf696d352b476e/src/Sushi.php#L74
Your code also errors if they have the array but it's empty which I think is unintended?
This PR removes the error allowing the test to pass successfully.

Fix error 'Trying to access array offset on value of type null'

---

src/Sushi.php

ID columns aren't always integers. For example if I'm retrieving data from the MailChimp API, each list's ID column looks something like `2f481d67b1`.
This PR simply checks for the integer type before calling ```increments()```.
ID columns are always unique though - so perhaps we want to make it unique if we're not incrementing. Thoughts?

Don't assume ID column is always an integer

---

.gitattributes
.styleci.yml

Enable StyleCI check. This repo is public so it's on a free tier. This repo needs to be enabled at https://styleci.io
---
Note: also adds `phpunit.xml` to export-ignore

Enable StyleCI check.

---

src/Sushi.php

Slight tweak to allow for a cache prefix set by a config file.  
:card_index:
Next step could be to create a config file that can be vendor:publish -ed :package:

Allow for a configurable cache prefix

---

src/Sushi.php
tests/SushiTest.php

This will automatically add primary keys if they're not specified and the model's incrementing variable is set to true.  Will use the model's primaryKey value for the column name.  This also removes the hardcoded "id" check and now checks against the model's primaryKey instead.

Auto add primary key if needed

---

src/Sushi.php
tests/SushiTest.php

Rework of https://github.com/calebporzio/sushi/pull/2 due to https://github.com/calebporzio/sushi/pull/2#issuecomment-580317930.
1. Do we just want to delete all rows instead of doing a full reset of the cache file and thus could assert a count of 0 after the flush call?
2. I couldn't really think of a good way to test https://github.com/calebporzio/sushi/pull/31/files#diff-1424272f1875ed72070adab615309d88R63-R70 due to point 1.

retrieve rows through a method

---

src/Sushi.php

Simple switch case to check what type of column to create depending on the value given.
The main reason was to support array values.

Support more columns in migrate function.

---

tests/SushiTest.php

This test `caches_sqlite_file_if_storage_cache_folder_is_available` fails on windows due to `\` instead of `/`
This PR solves that

Fix failing test on windows due to path separator

---

README.md

Added a "_**find more**_" link to your [sponsorware/docs](http://github.com/sponsorware/docs) 💰.

chore: add a "find more" link to Sponsorware/Docs

---

.gitattributes
composer.json

PHP 8 Support

---

src/Sushi.php
tests/SushiTest.php

EDIT: 
I rebased this PR branch onto the master branch and i noticed that it was fixed but slightly different. But i think doing a `array_key_exists` is easier to read also my PR has tests to verify that adding an auto increment primary key is working as intended.
------------------------
Original message :
Sushi checks if the definition of the primary key exists in the rows, if not it tries to automatically add it.
Checking this condition is wrong, this PR fixes that.
Before the PR if you do something like this
```php
class FooWithKey extends Model
{
use \Sushi\Sushi;
protected $rows = [
['id' => 5, 'foo' => 'bar', 'bob' => 'lob'],
['id' => 6, 'foo' => 'baz', 'bob' => 'law'],
];
}
```
You will get an error (defining the primary key column twice) when trying to migrate the table. …

Fix checking and adding primary key

---

README.md
phpunit.xml
phpunit.xml.bak
src/Sushi.php
tests/SushiTest.php

Hi Caleb 👋
Thank you for Sushi, I really love using it. 
I recently ran into a scenario where I was using `getRows()` to grab data from a third party API, but sometimes the API would return an empty array as its results. Looking into the Sushi trait, it looks like it depends on at least one row of data to be within the array, because it uses that row to work out the column structure. 
To get around this, I wrote two new methods that are invoked on the `migrate()` method. One is `createTable` and the other is `createTableWithNoData`. If there happens to be no rows available, this will look for a new `protected $columns` where you can define your own table structure, all within the model! I've used the same data types that you had in your original `migrate()` command to ensure …

Feature: Allow Sushi to work even when there is no data available.

---

src/Sushi.php
tests/SushiTest.php

This PR adds Sushi's generated database connection to the app config `database.connections` array, which makes it possible to use Sushi models with the `exists` database rule. Accomplishes the same thing as #80 but using Laravel's existing validation infrastructure.

Add support for using Sushi models with the `exists` validation rule

---

README.md
src/Sushi.php

Hello @calebporzio !
I think it's my first contribution here, so first of all thanks for this amazing package. It's simplicity does not equal show the value it provides.
That said, I am working on a project where we use `Sushi` to work with files stored in the filesystem.
This files represent the rows in the model, for each of them we get some properties to save along. The list of files is not static and can grow/shrink over time, and with that grows the number of attributes.
In the other day I tried to access my `sushi` model after creating one more file and got the error: `SQLSTATE[HY000]: General error: 1 too many SQL variables`.
After sometime debugging I found out that reducing the chunk size to `20` instead of the hardcoded `100` solves the issue. In other Sushi models we have 55 is …

[Mitigation] configurable chunk size for inserts

---

src/Sushi.php
tests/SushiTest.php

After introducing sushi to our project, our monitoring tool reported the following
error (stacktrace shortened for brevity):
```
PDOException: SQLSTATE[HY000]: General error: 1 table "schmelzkurve_scoring_table_results" already exists
#88 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(485): PDOStatement::execute
#87 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(485): Illuminate\Database\Connection::Illuminate\Database\{closure}
#86 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(685): Illuminate\Database\Connection::runQueryCallback
#85 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(652): Illuminate\Database\Connection::run
#84 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(486): …
```

Avoid error when creating database concurrently

---

src/Sushi.php
tests/SushiTest.php

At the moment, the connection name needs manually specifying when using the `exists` rule.
```php
Rule::exists('sushi.Model');
```
This kinda defeats the object of passing the class as the table name, as it should resolve the connection automatically 😆 
Thankfully, you just need to override the `getConnectionName()` method on the model.
Now, you can use:
```php
Rule::exists('Model');
// or
Rule::exists(Model::class);
```

Cannot use exists validation without manually specifying connection name & fix multiple model support

---

README.md

You must use both `$incrementing` and `$keyType` when using a string-based primary key with Sushi, else relationship lazy-loading and eager-loading completely break - this does not happen with normal Eloquent models so it's not documented anywhere 🥲

Add docs for using string-based primary keys

---

.github/workflows/tests.yml
composer.json

This PR extends the PHP constraints to support Laravel 9.
The `tests.yml` workflow has been updated, so that PHP 8.1 and Laravel 9 is also tested (and version combinations are excluded that do not work)

Add Laravel 9 support

---

.gitignore
src/Sushi.php
tests/SushiTest.php
tests/database/migrations/0000_00_00_000000_create_makis_table.php

In the current version, you cannot have `belongsTo` relationship from a sushi model to a non-sushi one. The reason behind this is that Laravel assumes the related model is in the same database as the one in which the relation is defined unless you explicitly set the connection name on the related model. With this PR, the default connection is used if the name is not specified. 
The first commit adds the failing test, the second one the fix.

Sushi models can relate to non-sushi models

---

README.md

Hey Caleb,
thanks for you awesome packages. ❤️ 
I changed the namespace in the _Validation_ section from `Model` to `Models`. The default directory name is in plural: https://laravel.com/docs/8.x/structure#the-models-directory
On a fresh Laravel installation you get an error with the namespace `App\Model\`.

Changed the Namespace in the documentation from "Model" to "Models"

---

README.md
src/Sushi.php
tests/SushiTest.php

Some of the sushi models in our systems contain a significant amount of rows. To speed some queries up, it would be useful to add some indexes to the cache tables. 
This PR allows for adjusting the table after the migration, useful for doing all kind of operations on the table. (Adding indexes, adding/adjusting columns etc).

Add after migration callback

---

phpunit.xml

These deprecated `phpunit` elements should be fixing
https://phpunit.readthedocs.io/zh_CN/latest/configuration.html#coverage

Replace deprecated phpunit configure

---

src/Sushi.php

This is useful if we want to change how the cache path generation is handled

Make Sushi Cache Path more customizeable

---

src/Sushi.php

Currently Sushi inserts rows straight into the database, which does not allow any "complex" data to be saved in rows, not even an array. Think of the use case  
```
[ 
"county" => "SomeCounty", 
"postCodes"=>[111,222,333]
]
```
This PR adds the ability to use the model's `$casts`, which allows Eloquent to cast arrays and other data as necessary into/from a string for saving to Sushi's internal SQLite database.

Add ability to use complex data types and casts

---

.gitignore
phpunit.xml
tests/SushiTest.php

There were two of the same test. (They were both marked skipped). I removed one of them.
Also phpunit was complaining that the xml config was using a deprecated schema so I updated it with "./vendor/bin/phpunit --migrate-configuration" and added the phpunit result cache to .gitignore

[Chore] Migrate phpunit config and remove duplicate test
